version: '3.7'

services:
  db:
      image: postgres
      restart:
              always
      environment: 
              POSTGRES_DB: postgres
              POSTGRES_USER: postgres 
              POSTGRES_PASSWORD: 1234
              ports:
                      "5433:5432"
      volumes:
        - data-volume:/var/lib/postgresql/data
  server:
    build: ./src
    command: bash -c "./run.sh"
    volumes:
            - ./src:/code
    ports:
            - "12345:12345"
    depends_on:
            - db
    networks:
            - default
volumes:
   data-volume: 
